//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Cheers_A02.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CheersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CheersEntities object using the connection string found in the 'CheersEntities' section of the application configuration file.
        /// </summary>
        public CheersEntities() : base("name=CheersEntities", "CheersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CheersEntities object.
        /// </summary>
        public CheersEntities(string connectionString) : base(connectionString, "CheersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CheersEntities object.
        /// </summary>
        public CheersEntities(EntityConnection connection) : base(connection, "CheersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Restaurants1> Restaurants1
        {
            get
            {
                if ((_Restaurants1 == null))
                {
                    _Restaurants1 = base.CreateObjectSet<Restaurants1>("Restaurants1");
                }
                return _Restaurants1;
            }
        }
        private ObjectSet<Restaurants1> _Restaurants1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Table> Tables
        {
            get
            {
                if ((_Tables == null))
                {
                    _Tables = base.CreateObjectSet<Table>("Tables");
                }
                return _Tables;
            }
        }
        private ObjectSet<Table> _Tables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Restaurants1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRestaurants1(Restaurants1 restaurants1)
        {
            base.AddObject("Restaurants1", restaurants1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTables(Table table)
        {
            base.AddObject("Tables", table);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheersModel", Name="Restaurants1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Restaurants1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Restaurants1 object.
        /// </summary>
        /// <param name="restId">Initial value of the RestId property.</param>
        /// <param name="restName">Initial value of the RestName property.</param>
        public static Restaurants1 CreateRestaurants1(global::System.Int32 restId, global::System.String restName)
        {
            Restaurants1 restaurants1 = new Restaurants1();
            restaurants1.RestId = restId;
            restaurants1.RestName = restName;
            return restaurants1;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RestId
        {
            get
            {
                return _RestId;
            }
            set
            {
                if (_RestId != value)
                {
                    OnRestIdChanging(value);
                    ReportPropertyChanging("RestId");
                    _RestId = StructuralObject.SetValidValue(value, "RestId");
                    ReportPropertyChanged("RestId");
                    OnRestIdChanged();
                }
            }
        }
        private global::System.Int32 _RestId;
        partial void OnRestIdChanging(global::System.Int32 value);
        partial void OnRestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RestName
        {
            get
            {
                return _RestName;
            }
            set
            {
                OnRestNameChanging(value);
                ReportPropertyChanging("RestName");
                _RestName = StructuralObject.SetValidValue(value, false, "RestName");
                ReportPropertyChanged("RestName");
                OnRestNameChanged();
            }
        }
        private global::System.String _RestName;
        partial void OnRestNameChanging(global::System.String value);
        partial void OnRestNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogoImageURL
        {
            get
            {
                return _LogoImageURL;
            }
            set
            {
                OnLogoImageURLChanging(value);
                ReportPropertyChanging("LogoImageURL");
                _LogoImageURL = StructuralObject.SetValidValue(value, true, "LogoImageURL");
                ReportPropertyChanged("LogoImageURL");
                OnLogoImageURLChanged();
            }
        }
        private global::System.String _LogoImageURL;
        partial void OnLogoImageURLChanging(global::System.String value);
        partial void OnLogoImageURLChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheersModel", Name="Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Table object.
        /// </summary>
        /// <param name="tableId">Initial value of the TableId property.</param>
        /// <param name="tableGUID">Initial value of the TableGUID property.</param>
        /// <param name="locatedIn">Initial value of the LocatedIn property.</param>
        public static Table CreateTable(global::System.Int32 tableId, global::System.Guid tableGUID, global::System.Int32 locatedIn)
        {
            Table table = new Table();
            table.TableId = tableId;
            table.TableGUID = tableGUID;
            table.LocatedIn = locatedIn;
            return table;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TableId
        {
            get
            {
                return _TableId;
            }
            set
            {
                if (_TableId != value)
                {
                    OnTableIdChanging(value);
                    ReportPropertyChanging("TableId");
                    _TableId = StructuralObject.SetValidValue(value, "TableId");
                    ReportPropertyChanged("TableId");
                    OnTableIdChanged();
                }
            }
        }
        private global::System.Int32 _TableId;
        partial void OnTableIdChanging(global::System.Int32 value);
        partial void OnTableIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TableGUID
        {
            get
            {
                return _TableGUID;
            }
            set
            {
                OnTableGUIDChanging(value);
                ReportPropertyChanging("TableGUID");
                _TableGUID = StructuralObject.SetValidValue(value, "TableGUID");
                ReportPropertyChanged("TableGUID");
                OnTableGUIDChanged();
            }
        }
        private global::System.Guid _TableGUID;
        partial void OnTableGUIDChanging(global::System.Guid value);
        partial void OnTableGUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocatedIn
        {
            get
            {
                return _LocatedIn;
            }
            set
            {
                OnLocatedInChanging(value);
                ReportPropertyChanging("LocatedIn");
                _LocatedIn = StructuralObject.SetValidValue(value, "LocatedIn");
                ReportPropertyChanged("LocatedIn");
                OnLocatedInChanged();
            }
        }
        private global::System.Int32 _LocatedIn;
        partial void OnLocatedInChanging(global::System.Int32 value);
        partial void OnLocatedInChanged();

        #endregion

    }

    #endregion

}
